const urlApi = 'https://admin.ikapunija.com/api',
  urlListRegion = 'https://restcountries.eu/rest/v2/all',
  apiToken = 'aWthcHVuaWphMjAyMXhhZmxvd3pAMTIxMzEwIV89',
  imageAgenda = 'https://admin.ikapunija.com/asset_image/agenda',
  imageBanner = 'https://admin.ikapunija.com/asset_image/banner',
  imageBeritaAlumni = 'https://admin.ikapunija.com/asset_image/berita_alumni',
  imageCdc = 'https://admin.ikapunija.com/asset_image/cdc/',
  imageGallery = 'https://admin.ikapunija.com/asset_image/gallery',
  imageAlbum = 'https://admin.ikapunija.com/asset_image/album',
  imageKtp = 'https://admin.ikapunija.com/asset_image/user_alumni/ktp',
  imageProfil = 'https://admin.ikapunija.com/asset_image/user_alumni/profil',
  imagePengumuman = 'https://admin.ikapunija.com/asset_image/pengumuman/',
  imageStruktur = 'https://admin.ikapunija.com/asset_image/foto_struktur'

export {
  urlApi,
  urlListRegion,
  apiToken,
  imageAgenda,
  imageBanner,
  imageBeritaAlumni,
  imageCdc,
  imageGallery,
  imageAlbum,
  imageKtp,
  imageProfil,
  imagePengumuman,
  imageStruktur,
}
